version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /dependabot
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /template
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /template
    schedule:
      interval: daily
